title: Cagri Kahraman # your name (or website title) here
logo: "/images/1517253345203.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Cagri (Chaa-raa) Kahraman.
  I work as Test Automation Lead Engineer at Bank of America.
  <br><br>
  I live in Charlotte, NC 
  <a href="https://www.linkedin.com/in/cagrikahraman/">View My LinkedIn Profile</a> 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
